spring:
  datasource:
    url: jdbc:h2:file:~/teams
    driver-class-name: org.h2.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
